---
providers:
    tvdb:
        apikey: "tvdbapikey"
        username: "tvdb_username"
        userkey: "tvdb_userkey"

notifiers:
    pushbullet:
        accessToken: "pushbullet access token"

indexers:
    torznab:
        - name: "Indexer 1"
          url: "url1"
          apikey: "apikey1"
        - name: "Indexer 2"
          url: "url2"
          apikey: "apikey2"

shows:
    - "Game of thrones"
    - "Suits"
    - "Blablabla"
    - "South Park"
