---
providers:
    tvdb:
        apikey: "tvdbapikey"

notifiers:
    pushbullet:
        accessToken: "pushbullet access token"

indexers:
    torznab:
        - name: "Indexer 1"
          url: "url1"
          apikey: "apikey1"
        - name: "Indexer 2"
          url: "url2"
          apikey: "apikey2"

downloaders:
    transmission:
        address: localhost
        port: 1234
        user: test
        password: testpasswd

shows:
    - "Game of thrones"
    - "Suits"
    - "Blablabla"
    - "South Park"
