package objects

const RECENTLY_AIRED_EPISODES_INTERVAL = 14

const (
	TORRENT_DOWNLOADING = iota
	TORRENT_SEEDING
	TORRENT_STOPPED
	TORRENT_DOWNLOAD_PENDING
	TORRENT_UNKNOWN_STATUS
)

const (
	RETENTION_FILE_PATH = "/var/run/flemzerd/retention.dat"
)
