baseURL = "/"
languageCode = "en-us"
title = "flemzer"
theme = "flemzer"

description = "Pouet"

Paginate = 4

[[menu.main]]
name = "Download"
weight = -50
url = "https://github.com/macarrie/flemzerd/releases"

[[menu.main]]
name = "Docs"
weight = -100
url = "/docs/"

[[menu.main]]
name = "GitHub"
weight = -10
url = "https://github.com/macarrie/flemzerd"
